### ISSUE TITLE
PATCH now throws 500

### ISSUE THREAD

**Issue by allthesignals** [MAPC/youth-match-v2#65]
```
curl 'https://dyee.mapc.org/api/positions/189' -X OPTIONS -H 'Access-Control-Request-Method: PATCH' -H 'Origin: http://youthjobs.mapc.org' -H 'Accept-Encoding: gzip, deflate, sdch, br' -H 'Accept-Language: en-US,en;q=0.8,la;q=0.6' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36' -H 'Accept: */*' -H 'Referer: http://youthjobs.mapc.org/jobs/189?email=arouault%40mapc.org&token=pz_cScdvohD-DsK6B3Cg' -H 'Connection: keep-alive' -H 'Access-Control-Request-Headers: authorization,content-type' --compressed ;
curl 'https://dyee.mapc.org/api/positions/189' -X PATCH -H 'authorization: Token token=pz_cScdvohD-DsK6B3Cg, email=arouault@mapc.org' -H 'Origin: http://youthjobs.mapc.org' -H 'Accept-Encoding: gzip, deflate, sdch, br' -H 'Accept-Language: en-US,en;q=0.8,la;q=0.6' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36' -H 'Content-Type: application/vnd.api+json' -H 'Accept: application/vnd.api+json' -H 'Referer: http://youthjobs.mapc.org/jobs/189?email=arouault%40mapc.org&token=pz_cScdvohD-DsK6B3Cg' -H 'Connection: keep-alive' --data-binary $'{"data":{"id":"189","attributes":{"category":"Information Technology","site_name":"Horace Mann School for the Deaf","title":"Document Imaging Specialist","external_application_url":null,"primary_contact_person":"Thomas P. Lally","primary_contact_person_title":"Teacher","address":null,"primary_contact_person_phone":"6176358534","site_phone":6176358534,"duties_responsbilities":"The Horace Mann High School student will use the Macintosh and Windows platforms to gain experience using the computer and peripheral devices   for scanning, and converting information to a digital format. Through a 1 year course on both platforms,  the students will be exposed to using various scanners, printers and storage devices to learn about the Document Imaging process, storage of such documents and Indexing and retrieval of such files. Students will gain experience using equipment that closely models current Document Imaging equipment, and will gain experience in all aspects of the Document Imaging field.","ideal_candidate":"\u06e1 Students will understand the types of graphic and digital files and the advantages and disadvantages of each. \u06e1 Students will gain an understanding of creating and working with  digital file formats. \u06e1 Students will understand the diferent types of scanners available. \u06e1 Students will understand the components of scanners & their function. \u06e1 Students will understand the advantages and disadvantages of each   scanner type and recognize the appropriate use of each. \u06e1 Students will understand document imaging related terminology. \u06e1 Students will understand the document imaging process and the steps it takes to complete it successfully.\\t \u06e1 Students will understand how a document imaging lab functions and gain an appreciation for safe and effective work habits ","open_positions":8},"relationships":{"applicants":{"data":[]}},"type":"positions"}}' --compressed
```

**Comment by mzagaja** [comment]
We determined from looking at the logs that the address attribute was added to the front end client without having been deployed to the back end and thus ActiveModel threw a 500 error when it received the unexpected attribute. Fixed by deploying to prod.

**Comment by allthesignals** [comment]
Hi Matt @mzagaja  - I'm still seeing a 500
`curl 'https://dyee.mapc.org/api/positions/207' -X PATCH -H 'authorization: Token token=secret, email=secret' -H 'Origin: http://youthjobs.mapc.org' -H 'Accept-Encoding: gzip, deflate, sdch, br' -H 'Accept-Language: en-US,en;q=0.8,la;q=0.6' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36' -H 'Content-Type: application/vnd.api+json' -H 'Accept: application/vnd.api+json' -H 'Referer: http://youthjobs.mapc.org/jobs/207?email=wmattgardner%40gmail.com&token=TwgLyBohf1cVd8XBXppF' -H 'Connection: keep-alive' --data-binary '{"data":{"id":"207","attributes":{"category":"Camp Counselor/ Summer Program Staff Support","site_name":"All Dorchester Sports League","title":"Youth Counselor","external_application_url":null,"primary_contact_person":"Stephanie Crawford","primary_contact_person_title":"Enrichment Coordinator","address":null,"primary_contact_person_phone":"6172871601","site_phone":6172871601,"duties_responsbilities":"Our youth counselors need to be  1. respectful 2. have good listening skills 3. be pro-active and energetic 4. patient 5. Adventurous! 6. Work well with others or is willing to  learn professional work skills","ideal_candidate":"Someone who can do all of the above!","open_positions":10},"relationships":{"applicants":{"data":[{"type":"applicants","id":"403"}]}},"type":"positions"}}' --compressed`
